version: "2.1"
services:
  mariadb:
    container_name: opensupports-db
    image: mariadb
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-opensupports}
      - MYSQL_USER=${MYSQL_DATABASE:-opensupports}
      - MYSQL_PASSWORD=${MYSQL_PASSWD:-changeme}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - ./database:/var/lib/mysql

  opensupports:
    container_name: opensupports
    image: cluttrdev/opensupports:4.11.0
    restart: always
    ports:
      - "5443:80"
    environment:
      - TIMEZONE=Europe/Berlin
    volumes:
      - ./config:/config
    depends_on: 
      - mariadb

